version: '3.8'

services:
  authserver:
    image: authserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  trackingserviceapp:
    image: trackingserviceapp:latest
    build:
      context: ../TrackingServiceApp
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  reportsserviceapp:
    image: reportsserviceapp:latest
    build:
      context: ../ReportsServiceApp
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
